/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.File;
import java.io.FileReader;
import java.io.Reader;

import static org.junit.Assert.*;
import static quotes.App.*;


public class AppTest {
    @Test public void testSearchByAuthorName() throws Exception {
        Gson gson =new Gson();
        File file = new File("../app/src/main/resources/recentquotes.json");
        Reader reader=new FileReader(file);
        Quotes[] quotes = gson.fromJson(reader,  Quotes[].class);
        reader.close();
        searchByAuthorName(quotes,"Klune");
    }

    @Test public void testSearchByTextContain() throws Exception {
        Gson gson =new Gson();
        File file = new File("../app/src/main/resources/recentquotes.json");
        Reader reader=new FileReader(file);
        Quotes[] quotes = gson.fromJson(reader,  Quotes[].class);
        reader.close();
        searchByAuthorName(quotes,"love");
    }
}
